### ISSUE TITLE
Add custom operators

### ISSUE THREAD

**Issue by kungfooman** [JuliaLang/JuliaParser.jl#77]
Hi all,

I'm pretty new to Julia and mostly coded in C/C++, so I would like to implement some C-ish operators like `->` to dereference pointers.

But since there is no `->` operator, I cannot create/overload such. Is there any easy way to simply define new operators, which can then be freely used? I glimpsed a bit over the code, but couldn't even find the "operator handling code" yet, lol. 

IMO that would make code much cleaner to read, e.g. from `unsafe_load(someptr).somefield` to `someptr->somefield`, especially when nested, like `linkedlist->next->next->prev->next` (imagine the `unsafe_load` version yourself :p). But this is not the only case, I would generally love to just add all kinds of custom operators.

Something like `JuliaParse.AddCustomOperator("->")`, maybe with settings like left/right binding powers (or whatever, I never wrote a full parser) for fine tuning. Would be epic if somebody has an idea how to accomplish this.

**Comment by ararslan** [comment]
Hey @kungfooman. This package doesn't actually do the parsing for Julia itself, but rather it's an experimental parser for Julia written in Julia. Julia's parser lives in the Julia repository and is implemented in Scheme. Regarding the design, you generally shouldn't need (or want!) to work directly with pointers in Julia, so it's unlikely to get its own syntax. In particular, `x->y` already means "create an anonymous function that accepts an argument `x` and returns `y`."

In general, questions like this should be posted to [Discourse](https://discourse.julialang.org), the official discussion/Q&A forum for Julia.

**Comment by ararslan** [comment]
Also, you can always define your own operator (though most ASCII-based common in other languages are taken, used by the Base library). As an example, you can define
```julia
→(ptr::Ptr, field::Symbol) = getfield(unsafe_load(ptr), field)
```
and use it like `a→:b`.

**Comment by kungfooman** [comment]
Thanks for the example, but I really dislike the syntax and I don't wanna mess around with Unicode operators.

And thanks for the hint, I didn't actually realized that C's dereference operator is Julia's lambda syntax.

I played a bit around with JuliaParser and figured it out how to add operators:

```
using JuliaParser

#length(JuliaParser.Lexer.ASSIGNMENT_OPS)

push!(JuliaParser.Lexer.ASSIGNMENT_OPS, Symbol("add"))

newops = [:add]
#:add in newops

function rewrite_op(i)
  if (i.head in newops)
    i.args = [i.head, i.args[1], i.args[2]]
    i.head = :call
  end
end

function rewrite(ast)
  # rewrite ast
  if typeof(ast) == Expr
    rewrite_op(ast)
  end
  # recursively rewrite all childs of ast
  for i in ast.args
    if typeof(i) == Expr
      rewrite(i)
    end
  end
end

test = JuliaParser.Parser.parse("1 add 2 add 3")

rewrite(test)

# add the new "operator"
function add(a, b)
  return a + b
end

eval(test) # returns 6

```

**Comment by oxinabox** [comment]
>I played a bit around with JuliaParser and figured it out how to add operators:

This is actually really cute, I can see maybe this kind of trick being useful for making DSLs 
(When pair with string macros).
Eg using this to add SQL operators.
.

But in this case not really a sensible thing to do, I think
You've effectively avoided writing a macro, by
1. invoking an alternate parser, with a modification you make to it before parsing
2. using a function (instead of a macro) to rewrite the AST
3. evaluating the rewritten AST.


All you really want to do is overload an operator.
And you want to avoid unicode.
There are enough unused operators in ANSI range.
Particularly since we can use multiple dispatch on ones we are not going to use for that combination of input types (`Ptr` and  `Symbol`)

For example:

### `..`

```julia
julia> (..)(ptr::Ptr, field::Symbol) = getfield(unsafe_load(ptr), field)
.. (generic function with 1 method)

julia> xp .. :bar    
```
note that `..` likes to have space around it.
Also I have a feeling it is up to be removed.

## `-`
```julia
julia> Base.:(-)(ptr::Ptr, field::Symbol) = getfield(unsafe_load(ptr), field)

julia> xp-:bar
```
I rather like this one, without spaces,
as it looks abit like the operator is `-:`, even that the `:` is actually part of the `:bar` Symbol
