### ISSUE TITLE
Why does the "pure julia implementation" seem to be stuck/abandoned? though nowhere marked as such

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/JuliaParser.jl#78]

**Comment by ararslan** [comment]
There's just no one focusing on it at this time. Julia's own parser is written in FemtoLisp; this Julia implementation isn't used by Julia itself, nor (at least directly) by any other existing project. It may be revived at some point provided someone has the time and a use case.

**Comment by rapus95** [comment]
Thanks for clarifying, just another question: what are the chances that julia will be fully selfhosted at a future point in time? is it an objective?

**Comment by ararslan** [comment]
There is currently discussion over the merits of that approach. One clear benefit of using Julia would be that we could more easily and accurately record and report syntax errors. The obvious counterpoint is that it makes it much harder to port Julia to new systems and architectures, since then to build Julia you first need a working build of Julia.

**Comment by waldyrious** [comment]
For future reference, there has been some discussion on this topic in [this thread](https://groups.google.com/forum/#!topic/julia-users/6FJ65U7n73M/discussion) (from when the discussion forum was still hosted in Google Groups).
